### ISSUE TITLE
System to generate Debian rootfs

### ISSUE THREAD

**Issue by jkent** [ARMWorks/NanoPi-tasks#1]
Currently FriendlyARM distributes their own premade Debian rootfs tarball.  We to be able to generate an equivalent system using debootstrap or multistrap.  One of my projects [dibs](https://github.com/jkent/dibs) which uses debootstrap could make a good starting point.

Features wanted:
- choose to remove locales, man pages
- add user defined packages

**Comment by forrestbao** [comment]
I think this is a very important thing. I prefer to have a rootfs that people can generate and customize on their own.

**Comment by jkent** [comment]
Been working on it.... after I get bluetooth stuff done I'll be moving it here.  See http://github.com/jkent/dibs

**Comment by jkent** [comment]
Closing, we now have https://github.com/ARMWorks/dibs
